const data = {
    nodes: [
      { person: 'Myriel', group: 'team1', multipleGroups: false },
      { person: 'Anne', group: 'team1', multipleGroups: false },
      { person: 'Gabriel', group: 'team1', multipleGroups: false },
      { person: 'Mel', group: 'team1', multipleGroups: false },
      { person: 'Yan', group: 'team2', multipleGroups: false },
      { person: 'Tom', group: 'team2', multipleGroups: false },
      { person: 'Cyril', group: 'team2', multipleGroups: false },
      { person: 'Tuck', group: 'team2', multipleGroups: false },
      { person: 'Antoine', group: 'team3', multipleGroups: false },
      { person: 'Rob', group: 'team3', multipleGroups: false },
      { person: 'Napoleon', group: 'team3', multipleGroups: false },
      { person: 'Toto', group: 'team4', multipleGroups: false },
      { person: 'Tutu', group: 'team4', multipleGroups: false },
      { person: 'Titi', group: 'team4', multipleGroups: false },
      { person: 'Tata', group: 'team4', multipleGroups: false },
      { person: 'Turlututu', group: 'team4', multipleGroups: false },
      { person: 'Tita', group: 'team4', multipleGroups: false },
    ],
    links: [
        { id: 0, source: 'Mel', target: 'Napoleon', value: 1, type: "with"},
        { id: 1, source: 'Myriel', target: 'Napoleon', value: 1, type: "with"},
        { id: 2, source: 'Gabriel', target: 'Myriel', value: 5 , type: "with"},
        { id: 3, source: 'Yan', target: 'Tom', value: 1 , type: "with"},
        { id: 4, source: 'Tuck', target: 'Myriel', value: 1 , type: "with"},
        { id: 5, source: 'Mel', target: 'Myriel', value: 1 , type: "with"},
        { id: 6, source: 'Mel', target: 'Myriel', value: 1 , type: "with"},
        { id: 7, source: 'Rob', target: 'Antoine', value: 1 , type: "with"},
        { id: 8, source: 'Tata', target: 'Titi', value: 1 , type: "with"},
        { id: 9, source: 'Tata', target: 'Toto', value: 1 , type: "with"},
        { id: 10, source: 'Tata', target: 'Tita', value: 1 , type: "with"},
        { id: 11, source: 'Tita', target: 'Toto', value: 1 , type: "with"},
      { id: 12, source: 'Anne', target: 'Myriel', value: 1, type: "about"},
      { id: 13, source: 'Napoleon', target: 'Myriel', value: 1, type: "about"},
      { id: 14, source: 'Napoleon', target: 'Rob', value: 1 , type: "about"},
      { id: 15, source: 'Tom', target: 'Cyril', value: 1 , type: "about"},
      { id: 16, source: 'Tuck', target: 'Mel', value: 1 , type: "about", with_id: 4},
      { id: 17, source: 'Tuck', target: 'Myriel', value: 1 , type: "about", with_id: 4},
      { id: 18, source: 'Tata', target: 'Tutu', value: 1 , type: "about", with_id: 9},
      { id: 19, source: 'Tita', target: 'Titi', value: 1 , type: "about"},
      { id: 20, source: 'Tita', target: 'Turlututu', value: 1 , type: "about"},
      { id: 21, source: 'Rob', target: 'Turlututu', value: 1 , type: "about", with_id: 7},
    ],
  };
  

  export default data;